# Generated by Django 5.1.3 on 2024-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_category_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_en_us',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
